### ISSUE TITLE
Possibility to replace whole array by another one

### ISSUE THREAD

**Issue by zeleznypa** [nette/neon#19]
Several times we had to replace array by another array instead of merging them:

For example:
```neon
[default]
    test: [a,b,c,d]
[test < default]
    test: [b,f,m,l]
```

And we need to give `array('b', 'f', 'm', 'l')` instead of `array('a', 'b', 'c', 'd','f', 'm', 'l')`

It could be useful to have possibility to "force replace" for example:  using prefix before the array name.
```neon
[default]
    test: [a,b,c,d]
[test < default]
    !test: [b,f,m,l]
```

**Comment by dg** [comment]
Use 
```neon
[default]
    test: [a,b,c,d]
[test < default]
    test!: [b,f,m,l]
```

**Comment by zeleznypa** [comment]
:+1:  It is really great. Thanks David
