### ISSUE TITLE
What are the supported formats inside an entity

### ISSUE THREAD

**Issue by moufmouf** [nette/neon#22]
I just discovered Neon and love the way it works. Especially, I love the notion of entity.

Now, I have a question about the supported syntax inside an Entity.

I've noticed that this is OK:

``` neon
entity0: Column(name=Homer, phones=[ home: 555-6528, work: 555-7334 ])
```

This is ok too:

``` neon
entity: Column(
    name: Homer
    phones: [ home: 555-6528, work: 555-7334 ]
)
```

But this yields what I would deem to be an unexpected result:

``` neon
entity2: Column(
    name: Homer
    phones:
        home: 555-6528
        work: 555-7334
)
```

In the attributes array, "home" and "work" are at the same level as "name" and "phones". I would have expected those keys to be in the "phones" key.

Also, this piece of code fails to parse:

``` neon
entity2: Column(
    name: Homer
    phones:
     - 555-6528
     - 555-7334
)
```

Is this considered a bug? If not, is there a specification of the NEON format somewhere explaining what is ok and what is not?
Could this be considered as a possible enhancement?

**Comment by JanTvrdik** [comment]
Neon parser has two modes – block mode and inline mode. In block mode indentations are significant, in inline mode indentation does not matter. The entity content is currently parse with the inline mode, therefore it does not understand indentations and you must you braces to define complex structures.

I don't know if using block mode instead would be an issue.
