### ISSUE TITLE
Different behaviour for : and = in strings

### ISSUE THREAD

**Issue by hason** [nette/neon#27]
```yaml
name: d:g
```
is fine, but
```yaml
name: d=g # name= d=g
```
throws `Error: Unexpected '=' on line 1, column 8.`

**Comment by dg** [comment]
After the colon must be a space but after the `=` may not be. This behavior can be changed, but it is a big BC break.

**Comment by Majkl578** [comment]
Neon is officially compatible with INI?

**Comment by dg** [comment]
No.

**Comment by hason** [comment]
In YAML it is possible to write

```yaml
foo: foo: bar # same as foo "foo: bar"
```

Why not in NEON?

I would like to write:
```yaml
foo: foo=bar
```
without quotations.

**Comment by dg** [comment]
So fa no one needed it, probably it is not useful in practice.

**Comment by Majkl578** [comment]
> In YAML it is possible to write
> ```yaml
> foo: foo: bar
> ```

No, it is not, it is illegal syntax. I.e. Symfony Yaml component fails with this error: *Uncaught Symfony\Component\Yaml\Exception\ParseException: A colon cannot be used in an unquoted mapping value at line 1 (near "foo: foo: bar")*.

**Comment by hason** [comment]
It was possible in Symfony 2. And yes, it is illegal. So I have solved a problem with ``=``: https://github.com/symfonette/neon-integration#expression
