### ISSUE TITLE
Octal values is malformed

### ISSUE THREAD

**Issue by adambisek** [nette/neon#31]
When I write chmod octal value, leading zero is stripped and an integer returned:

Example code:
`fileMode: 0777` -> returns int(777)

In PHP (and eg. Symfony Container as well) is it intepreted as an octal value and converted to integer:
`var_dump(0777);` // int(511)

I hope this is not intended behaviour, may we solve it?

**Comment by dg** [comment]
This is intended https://github.com/nette/neon/blob/de1c6d1ec0c3efa592777414561714bcb9f4a278/tests/Neon/Decoder.phpt#L56

**Comment by adambisek** [comment]
I suppose that is an method to make neon syntax more user-friendly.

What would you recommend please?

At this moment is only suitable solution to make it string, but it not so smart and easy to use (we're using it for chmod function and we have to cast that string to octal everywhere we use it).

**Comment by Majkl578** [comment]
@adambisek you can enter decimal value I guess, e.g. 511 for 777.

**Comment by dg** [comment]
The question is whether to add support for octal numbers. It is BC break and they are used rarely (probably only for chmod and chmod is configured via neon rarely too). 

Or we can introduce new syntax like `octal(777)`.

**Comment by adambisek** [comment]
Thanks for replies guys.
On the other side, I admit that PHP behaviour is a bit tricky.

But, my personal opinion is, the behaviour should be like PHP variable (for example config in an array).
By the way, it is not about PHP only, for example Javascript does the same thing: https://jsfiddle.net/yz5wagvg/
Stripping leading zeros and creating int is a mathematical solution, not programmatical.
When anybody writes `var: 0123` and expects an `int(123)`, it is wrong.

Anyway, if you really don`t want BC break, the introduced new syntax is less painful than string value (and calling `octdec ` in PHP script).

**Comment by dg** [comment]
hex `0x123` and binary `0b10110` syntax is clearly distinguished from dec numbers, but octal `0123` is not. It is historic convention (programmatical, not mathematical) from the sixties and makes a lot of complications in JavaScript (and is [deprecated](https://developer.mozilla.org/cs/docs/Web/JavaScript/Reference/Global_Objects/parseInt#ECMAScript_5_removes_octal_interpretation)). So I don't like to adopt it. 

Other possible syntax is `0o777`.

**Comment by adambisek** [comment]
Yes, syntax `0o777` I like, that`s good.
What`s next? Some voting or have I to send PR?

**Comment by dg** [comment]
`0o777` is the same as `0o0777`. Leading zeros has no meaning.

**Comment by adambisek** [comment]
Wow, that was quick. Thank you!
