### ISSUE TITLE
Will there be support for HHVM?

### ISSUE THREAD

**Issue by adambisek** [nette/neon#32]
Currently seems to be unsupported HHVM:
Fatal error: Arrays are not allowed in class constants in /vendor/nette/neon/src/Neon/Decoder.php on line 20

Will it be improved to support HHVM?

**Comment by dg** [comment]
As soon as HHVM will be compatible with PHP. https://github.com/facebook/hhvm/issues/4277

**Comment by adambisek** [comment]
Didn't know. Thanks.
