### ISSUE TITLE
Documentation: There is no grammar definition

### ISSUE THREAD

**Issue by jkufner** [nette/neon#38]
- bug report? yes
- feature request? no
- version: *

### Description

There are few examples on website, but otherwise there is nothing else.

To fully understand the syntax of the file a grammar definitions are required. Take a look at http://json.org/ for a good example.

### Steps To Reproduce

1. Try to read the documentation. 
2. Bug: There is no documentation.

**Comment by JanTvrdik** [comment]
@jkufner Neon is whitespace sensitive language. Writing readable grammar for whitespace sensitive languages is usually impossible, unless you cheat by using some magic indentation tokens.

**Comment by jkufner** [comment]
@JanTvrdik White space characters are tokens just like any other. Depth of indentation is a bit tricky, but it is better to have a readable grammar with a magical indentation token than having no grammar at all. How I am supposed to know how to write my config file when there is no specification?

**Comment by dg** [comment]
@jkufner Could you try to create something like grammar definition?

**Comment by iRaziul** [comment]
I would like to know about the performance compared to **json** in php.
May be json is the clear winner in performance section
