### ISSUE TITLE
PHP 8.0 decoding problem

### ISSUE THREAD

**Issue by dlxko** [nette/neon#58]
Version: 3.2.1 / dev-master

### Bug Description

I have downloaded Nette basic project on a server with PHP 8.0RC2.
Just run the web and Neon throws an exception "Bad indentation on line 6, column 2." on these lines.
When I remove line 5, everything works fine.

application:
 5:    →   errorPresenter:·Error
 6:    →   mapping:
 7:    →   →   *:·App\*Module\Presenters\*Presenter

### Steps To Reproduce
composer create-project nette/web-project nette-blog --ignore-platform-req
Installing nette/web-project (v3.0.7)

https://ne-on.org/#saved-RY6xCsMwDERn+ys8Zyt08tah3QqlcxZhi2BILCE7pfn7ynFIJ53ujscxCCxYUYq31gLznALURNlbgyIkL8GCWQve3dtvzaKtlCctmMG7G/M4PCmuM45nt4zDqRVbsJQD+eUkne8uVxdhK5rH1COS2qj83+QyqVFh6rKh5JMC6lojtO6z2oL3ro/zgFBJNu+DIFTs5g8=
### Expected Behavior
This input file will be parsed

**Comment by mabar** [comment]
It was an opcache bug and is already fixed 
https://bugs.php.net/bug.php?id=80255

**Comment by dlxko** [comment]
Seems to be fixed in RC3 👍

**Comment by slischka** [comment]
Narazil jsem na to samé, mám RC1 a nevrčí to. Pro testování jsem natvrdo vypnul opcache a rozjelo se :)
