### ISSUE TITLE
URL in array can not contain "=" character

### ISSUE THREAD

**Issue by janbarasek** [nette/neon#60]
Version: 3.2.1

### Bug Description
In case of NEON:

```yaml
urls:
    - https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.23.0/polyfill.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_HTML
    - https://baraja.cz/css/styles.css
```

Is it parsed to:

<img width="816" alt="Snímek obrazovky 2020-12-17 v 10 11 32" src="https://user-images.githubusercontent.com/4738758/102467156-3d9a0f00-4050-11eb-8360-d3a86c2f09ab.png">

Because the second URL contains `=` character.

### Expected Behavior & Possible Solution
I think in the context of the URL (starting with `#^(https?|ftp)://#`) NEON should ignore character `=` in the URL and keep it as a string.

Thanks!

**Comment by mabar** [comment]
Behavior might be unexpected (I didn't know about special meaning of = too), but proposed solution is just confusing. Your example have same result as `- a=b` and as such it's at least consistent.

**Comment by dg** [comment]
`=` has special meanin in NEON and it cannot be simply changed due to backward compatibility.

**Comment by janbarasek** [comment]
Ok, I understand.
