### ISSUE TITLE
leading zeros trimmed from numeric string

### ISSUE THREAD

**Issue by Ciki** [nette/neon#64]
Hi, is trimming leading zeros from numeric string a feature or a bug?

```
- 0907123456
```
valid mobile number gets parsed as `907123456` integer. I know I can use quotes to parse it as string. I was just used to not having to use quotes in neon syntax. If this is a feature it could help someone else if it was mentioned in docs

**Comment by dg** [comment]
I would probably stay with parsing a number starting with zero as a number for compatibility reasons. If you write it in the documentation, that'll be great.
