### ISSUE TITLE
Octal numbers are translated as string

### ISSUE THREAD

**Issue by h4kuna** [nette/neon#70]
Version: 3.4.2

### Bug Description
After update from 3.4.1 neon translate octal numbers as string

### Steps To Reproduce
**EDIT:** missing extension bcmath

Neon configuration
```neon
- h4kuna\Uget\File(0o666)
```

```php
namespace h4kuna\Uget;

final class File
{
	public function __construct(private int $permission)
	{
	}
}
```
v3.4.1 create container method like
```php
public function createService012(): h4kuna\Uget\File
{
	return new h4kuna\Uget\File(438);
}
```
v3.4.2 create container method like
```php
public function createService012(): h4kuna\Uget\File
{
	return new h4kuna\Uget\File('438');
}
```

I get exception **TypeError: h4kuna\Uget\File::__construct(): Argument #1 ($permission) must be of type int, string given**

### Expected Behavior
Same as v3.4.1

**Comment by h4kuna** [comment]
I found the [change commit](https://github.com/nette/neon/commit/1e453c4500ce0d05008c5559fd9fa7ec93c65b24#diff-65ce0526bea31ea445ab42a00ace919a131d6a64974b4c216ef8305fb4348a18R69) and I did't have to install bcmath extension.

If I install extension, the transform works fine. But here is different behavior for small integers.

**Comment by dg** [comment]
fixed
